# Configuration file for Beatblocks 0.1.0-beta

# Allow players to run debug commands.
# Most debug commands do nothing useful, since they are for testing how inner methods work.
debug: false

# Allow players to see stack traces of exceptions when commands fail, etc. Setting this to false will still show the message of the exception.
show-stacktrace: true

# Authtoken for ngrok. Go to https://dashboard.ngrok.com/get-started/your-authtoken and copy-paste your authtoken here.
ngrok-authtoken: